/**
 * Explains which rule picked the caption track the bridge activates.
 */
export const CAPTION_TRACK_SELECTION_SOURCE = {
    DefaultFlag: 'default-flag',
    PlayerResponse: 'player-response',
    First: 'first',
} as const;

/**
 * Stable selection-rule names appended to bridge activation actions.
 */
export type CaptionTrackSelectionSource =
    (typeof CAPTION_TRACK_SELECTION_SOURCE)[keyof typeof CAPTION_TRACK_SELECTION_SOURCE];

/**
 * Track object taken verbatim from the player tracklist plus the rule that
 * chose it.
 */
export type CaptionTrackSelection = {
    track: unknown;
    source: CaptionTrackSelectionSource;
};

const AUTO_GENERATED_TRACK_KIND = 'asr';

/**
 * Picks the caption track that matches the video's own language rather than
 * whichever track YouTube lists first.
 *
 * Creators often upload a translated subtitle track that omits the sponsor
 * read entirely, and YouTube lists manual tracks before auto-generated ones,
 * so the first entry is frequently the wrong transcript for promo detection.
 * The player's `is_default` flag and the player response's
 * `defaultCaptionTrackIndex` both name the track YouTube would enable itself,
 * which follows the audio language.
 *
 * @param tracks - Untrusted `getOption('captions', 'tracklist')` value.
 * @param playerResponse - Untrusted `getPlayerResponse()` value, if any.
 * @returns Chosen track and the rule that selected it, or null without tracks.
 */
export function selectPreferredCaptionTrack(
    tracks: unknown,
    playerResponse: unknown,
): CaptionTrackSelection | null {
    if (!Array.isArray(tracks) || tracks.length === 0) {
        return null;
    }
    const entries: unknown[] = tracks;

    const flaggedDefault = entries.find(
        (track) => readProperty(track, 'is_default') === true,
    );
    if (flaggedDefault !== undefined) {
        return {
            track: flaggedDefault,
            source: CAPTION_TRACK_SELECTION_SOURCE.DefaultFlag,
        };
    }

    const responseDefault = findPlayerResponseDefaultTrack(
        entries,
        playerResponse,
    );
    if (responseDefault !== undefined) {
        return {
            track: responseDefault,
            source: CAPTION_TRACK_SELECTION_SOURCE.PlayerResponse,
        };
    }

    return {
        track: entries[0],
        source: CAPTION_TRACK_SELECTION_SOURCE.First,
    };
}

/**
 * Resolves `captions.playerCaptionsTracklistRenderer.defaultCaptionTrackIndex`
 * back to a tracklist entry by `vssId`, or by language and auto-generated
 * kind when the ids are absent.
 *
 * @param tracks - Non-empty player tracklist.
 * @param playerResponse - Untrusted player response.
 * @returns Matching tracklist entry, if the response names one.
 */
function findPlayerResponseDefaultTrack(
    tracks: unknown[],
    playerResponse: unknown,
): unknown {
    const renderer = readProperty(
        readProperty(playerResponse, 'captions'),
        'playerCaptionsTracklistRenderer',
    );
    const captionTracks = readProperty(renderer, 'captionTracks');
    const defaultIndex = readProperty(renderer, 'defaultCaptionTrackIndex');
    if (
        !Array.isArray(captionTracks) ||
        typeof defaultIndex !== 'number' ||
        !Number.isInteger(defaultIndex)
    ) {
        return undefined;
    }
    const defaultTrack: unknown = captionTracks[defaultIndex];
    if (defaultTrack === undefined) {
        return undefined;
    }

    const vssId = readProperty(defaultTrack, 'vssId');
    if (typeof vssId === 'string') {
        const byVssId = tracks.find(
            (track) => readProperty(track, 'vss_id') === vssId,
        );
        if (byVssId !== undefined) {
            return byVssId;
        }
    }

    const languageCode = readProperty(defaultTrack, 'languageCode');
    if (typeof languageCode !== 'string') {
        return undefined;
    }
    const autoGenerated = isAutoGeneratedTrack(defaultTrack);
    return tracks.find(
        (track) =>
            readProperty(track, 'languageCode') === languageCode &&
            isAutoGeneratedTrack(track) === autoGenerated,
    );
}

/**
 * Both the player response and the tracklist mark auto captions with
 * `kind: "asr"`; the tracklist also prefixes their `vss_id` with `a.`.
 *
 * @param track - Track from either source.
 * @returns Whether the track is auto-generated.
 */
function isAutoGeneratedTrack(track: unknown): boolean {
    if (readProperty(track, 'kind') === AUTO_GENERATED_TRACK_KIND) {
        return true;
    }
    const vssId = readProperty(track, 'vss_id');
    return typeof vssId === 'string' && vssId.startsWith('a.');
}

/**
 * Reads one property from page-owned data without assuming its shape.
 *
 * @param value - Untrusted object or primitive.
 * @param key - Property name.
 * @returns Property value, or undefined for non-objects.
 */
function readProperty(value: unknown, key: string): unknown {
    if (value === null || typeof value !== 'object') {
        return undefined;
    }
    return Reflect.get(value, key);
}
